### ISSUE TITLE
Some general questions 

### ISSUE THREAD

**Issue by qur2** [DylanPiercey/tusk#2]
Hi, 

I'm looking very hard at frameworks/libraries for an upcoming project. The "default" choice seem to be react but after trying it, while I like the component approach, I didn't like how I ended up binding all event handlers to `this`. 
After looking further, I found your project, deku, virtual-component and mercury. 

What I like about yours (in theory, didn't try yet) is the mount onto and the with+context. 

What I'm wondering is how does your library compare to those alternatives. Also, what about Dom diffing?  Is it on par with those? Does it have any real world example built on it? Why did you build it in the first place? 

Last but not least: it seems that there are a handful of librairies with this name already. Maybe you should consider changing? 

Thanks for your nice work and sorry for the length of my post!

**Comment by DylanPiercey** [comment]
@qur2 thanks for considering tusk!

I made tusk for quite a few reasons, as mentioned in the readme.

I particularly like that tusk has way less "gotchas" than react for things like html attributes.
Things like "class -> classNames", "for -> htmlFor" and others can be annoying for devs that want to jump in. In tusk the only difference that you need to make your designers/devs aware of is that all elements must be closed and that the interpolation is "{ }".

The output html of tusk is also a lot more reasonable, no data-reactids and generally the html tusk can bootstrap off of is exactly what a human could right. (React does a lot of tricky span insertions and such). This makes tusk great even if you are only rendering on the server (static pages).

Tusk is also a decent amount faster than anything I could test (deku, mercury, react). It is minimal extremely optimized for dom diffing.

The biggest thing with tusk is that it does not manage state at all. Tusk is a library for taking two virtual dom trees and diffing them, usually from the top down.

To handle state with tusk you have a few options:
- Use a library like "immstruct" or "baobab" and re-render on state changes from the top down.
- Use the "ignore" attribute on stateful nodes and manually perform dom manipulations or use tusk to render just that node again (usually I setup state updater functions in the onMount and cleanup onDismount).

Personally the first one works well for me because I like to have all of my state outside of my view for ui flexability in the future.

---

In the future I will re-write tusk (but maintain the exact same api) in javascript instead of coffeescript since the coffeescript was mainly just during beta (which I hope to be leaving soon).

Currently only some example sites are built with tusk but we are looking into using it at my company within the next couple months, but we have been slowed down a little with large workloads.

I could consider a name change however my requirements would be that it is short and available on npm. If you have any other questions or need more details just let me know.

**Comment by qur2** [comment]
Hi,

Thanks for that long answer. Would love to see a RC :) I'm kind of lost in all those tools, then you get to choose your flux implementation and it get even harder.

For the name, the only thing that came to my mind is v-ride for virtual-ride since your library mounts component onto rather than into :p Then I thought it sounds good :D and it's free on NPM.

I'll let you know if/when I come to an experiment with this.

Thanks!
